### ISSUE TITLE
Re-generate token only on data changes or after a certain amount of lifetime

### ISSUE THREAD

**Issue by Ocramius** [Ocramius/StorageLessSession#5]
A token should only be re-generated after:
 - the data changed
 - its lifecycle has past a certain amount of time (10% of lifetime, for example)

This greatly reduces crypto CPU usage, as well as prevents slamming the cookies due to race conditions.

Our todo list is:

- [x] track data change;
- [x] configure the refresh lifetime (10% can be the default);
- [x] ensure that the token cookie **is not** sent when there is a valid token in request and user hasn't changed the session data;
- [x] ensure that the token cookie **is** sent when there is a valid token in request and is the refresh time (current time represents X% of iat and exp claims);

**Comment by Ocramius** [comment]
#11 implements points 1 and 3

**Comment by malukenho** [comment]
It was completed right?

**Comment by Ocramius** [comment]
@malukenho indeed!
